FROM python:3.10

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

ARG PERSIST_DIRECTORY=db
ARG MODEL_TYPE=LlamaCpp
ARG MODEL_PATH=/code/models/llama-2-7b.ggmlv3.q5_0.bin
ARG EMBEDDINGS_MODEL_NAME=all-MiniLM-L6-v2
ARG MODEL_N_CTX=10000
ARG MODEL_N_BATCH=1024
ARG TARGET_SOURCE_CHUNKS=4
ARG SOURCE_DIRECTORY=../source_documents

ENV PERSIST_DIRECTORY=$PERSIST_DIRECTORY
ENV MODEL_TYPE=$MODEL_TYPE
ENV MODEL_PATH=$MODEL_PATH
ENV EMBEDDINGS_MODEL_NAME=$EMBEDDINGS_MODEL_NAME
ENV MODEL_N_CTX=$MODEL_N_CTX
ENV MODEL_N_BATCH=$MODEL_N_BATCH
ENV TARGET_SOURCE_CHUNKS=$TARGET_SOURCE_CHUNKS
ENV SOURCE_DIRECTORY=$SOURCE_DIRECTORY

COPY ./app /code/app

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]
